name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the Preprocess image
      run: docker build ./boston_housing/preprocess_data --tag japisuru/kubeflow-pipelines-preprocess-data
    - name: Push the Preprocess image
      run: docker push japisuru/kubeflow-pipelines-preprocess-data
    - name: Build the Train image
      run: docker build ./boston_housing/train --tag japisuru/kubeflow-pipelines-train
    - name: Push the Train image
      run: docker push japisuru/kubeflow-pipelines-train
    - name: Build the Test image
      run: docker build ./boston_housing/test --tag japisuru/kubeflow-pipelines-test
    - name: Push the Test image
      run: docker push japisuru/kubeflow-pipelines-test
    - name: Build the Deploy image
      run: docker build ./boston_housing/deploy_model --tag japisuru/kubeflow-pipelines-deploy-model
    - name: Push the Deploy image
      run: docker push japisuru/kubeflow-pipelines-deploy-model
